name = "northstar-erp-next"
main = ".open-next/worker.js"
compatibility_date = "2026-04-13"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "northstar-erp-next"

[[d1_databases]]
binding = "DB"
database_name = "northstar-erp-d1"
database_id = "1509ec0f-9457-4b1e-9069-bb4c49419a1b"
